version: "1.0"
info:
  model: int-scaffold
packages:
- name: SttCustomersProject
  gitServerName: sttlab GH
  gitUrl: https://github.com/sttlab-tech
  gitUsername: sttlab-tech
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: licensed
services:
- serviceName: project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:db_azuresql_dada_edge
  packages:
  - name: SttCustomersProject
    version: "1.0"
configurationVariables:
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.databaseName
  : sqldb
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.driverType
  : Progress® DataDirect®
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.trustStore
  : ""
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.networkProtocol
  : ""
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionManagerSettings.poolable
  : "true"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.user
  : sttlab
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.portNumber
  : "1433"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.keyStore
  : ""
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.password
  : "{AES}xQJbA1N3SVslXYLJd7vQXHtoPSIUr5vmkgNS5mqAKjw="
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.serverName
  : sttlab.database.windows.net
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionEnabled
  : "false"
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.dbType
  : MSSQL
  ? artConnection.SttCustomersProject.project.sttcustomers.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.db_azuresql_dada_edge.connectionSettings.otherProperties
  : loginTimeout=60;
